CREATE TABLE COEX_ADJ_TABLE(

)


CREATE TABLE COEX_ADJ_TABLE(
		"NODENAME" NUMBER(10, 0) NOT NULL,
		"ADJLIST" VARCHAR2(2000) NOT NULL
);

CREATE TABLE COEX_SHORTEST_TABLE(
		"NODENAME" NUMBER(10, 0) NOT NULL,
		"SHORTLIST" VARCHAR2(2000) NOT NULL
);

CREATE TABLE COEX_PATH_TB(
PATH_FROM_NODE_NO number(10) NOT NULL, 
PATH_TO_NODE_NO number(10) NOT NULL, 
PATH_PATH varchar2(1000) NOT NULL);

CREATE TABLE COEX_SCHEDULE_TB(
SCHEDULE_NO number(10) primary key,
MEM_ID varchar2(20) default 'annonymous',
SCHEDULE_DATE varchar2(10),
SCHEDULE_START_TIME varchar2(10),
SCHEDULE_END_TIME varchar2(10),
SCHEDULE_EVENT_LIST varchar2(1000),
SCHEDULE_TIME_LIST varchar2(1000),
SCHEDULE_NODE_LIST varchar2(1000),
SCHEDULE_TIME_TABLE varchar2(1000),
SCHEDULE_IMG_LIST varchar2(1000),
PREFNO number(10),
SCHEDULE_EVAL number(1,2)
)



